name: ORFeome
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - bowtie=1.3.1
  - cutadapt
  - samtools
  - trim-galore
  - fastqc
  - sra-tools
  - pip
  - r-base=4.2
  - bioconductor-deseq2
  - r-openxlsx
